### ISSUE TITLE
Riot Games/Launcher (explenation below)

### ISSUE THREAD

**Issue by Spieler2301** [Mixaill/awesome-gog-galaxy#108]
_I recently found out that all games from Riot are launched with one .exe, so it would be possible_

Your request will help someone to create a new integration. You don't have to fill everything, just write about what you know and be concise. Thanks!

**Identification**
[Riot Games](https://www.riotgames.com/de) (idk if they have an API)

**Integration type**
multiple single games

**Present in [Galaxy API available integrations list](https://github.com/gogcom/galaxy-integrations-python-api/blob/master/src/galaxy/api/consts.py#L4)?**
Yes, but only if you know the arguments for stating the games

**Supported platforms**
PC(Win)

**Store content / licenses**
LoL / TFT / Runterra / Valorant (all from Riot Games

**Coverage**
It has 4 games as of right now

**Galaxy features**
Which Galaxy 2.0 features could be potentially implemented (for at least one game)? Choose from:
- importing owned games
- detect locally installed games / install / launch / uninstall
- game last played time / total played time
- friends and their statuses
- chat

**Comment by BanCrash** [comment]
Why is the actual riot integration not enough for filling this issue?

**Comment by Mixaill** [comment]
IDK

@Spieler2301 There is Riot integration: https://github.com/urwrstkn8mare/galaxy-riot-integration
