### ISSUE TITLE
Path of Exile Integration is no longer available

### ISSUE THREAD

**Issue by scutajar** [Mixaill/awesome-gog-galaxy#11]
@nyash-qq's Path of Exile integration seems to have been taken down from GitHub.

**Comment by ziplock9000** [comment]
Probably because it's not complete, which is by the admission of the developer a few days ago.

**Comment by nyash-qq** [comment]
Took it off cause GLX could not handle the platform. Should work now, although still no achievements and platform icon, but that's by the GLX side.
Also added readme on how to install the plugin.
