### ISSUE TITLE
Indiegala

### ISSUE THREAD

**Issue by Mixaill** [Mixaill/awesome-gog-galaxy#13]
ID whitelisting: ❌

Originally reported by @RaptorPharaoh

> It's similar to Humble Bundle DRM Free downloads, probably this is the easiest to make.

**Comment by luxzg** [comment]
More details for anyone interested...

Store page: https://www.indiegala.com/
Profile / games page: https://www.indiegala.com/profile?user_id= (followed by unique user id)

It is a game store, offers frequent bundles, indie games, free games, etc.

Offers keys for other platforms, mostly Steam, but there's also all kinds of other keys, specially for indie platforms.

Has my +1

**Comment by UncleGoogle** [comment]
If this is mostly about keys from Steam or other DRM-s, why having separate integration for it? Is Steam and other launcher-integrations sufficient? Won't you activate those keys just after buying them?

**Comment by luxzg** [comment]
Its not just about keys, there are DRM free downloads there as well. And if Galaxy is to be center of all our games, it should show info from all stores too.

Also honestly, and I know I'm not alone, not all keys get activated right away, I have about 1600+ activated games currently seen through Galaxy, but I have roughly same amount still in unactivated keys and undownloaded installers in my backlogs that stretch from Bundlestars, Humble, Indiegala, Gamersgate, Nuveem, Amazon, etc, all the way to some now defunct services.

Having any way beyond email receipts + Excel to track all those games would be awesome.

I also use IsThereAnyDeal for game list tracking, but that's a bit more than fancy Excel, no real links to my actual store / launcher downloads and installers (be it DRM or DRM-free)

**Comment by luxzg** [comment]
Info: Indiegala was added as supported ID here
https://github.com/gogcom/galaxy-integrations-python-api/issues/34

**Comment by burnhamup** [comment]
I've got a start on the Showcase library (where the freebie downloads are stored). I've got about 100 games showing up in GOG Galaxy now.

https://github.com/burnhamup/galaxy-integration-indiegala

**Comment by michaelwexler** [comment]
Should this be closed?  The integration is incomplete, doesn't show up in the GOG search, and has no easy end-user installation process.  Perhaps we can keep this open til some of that occurs?
