### ISSUE TITLE
Lodestone/FFXIV intergration

### ISSUE THREAD

**Issue by crypticarchon** [Mixaill/awesome-gog-galaxy#16]
is it possible to integrate the lodestone achievements for the people that dont play FFXIV on steam?

**Comment by effcol** [comment]
@Mixaill Looks like someone's developing a FFXIV integration to add this:
[https://www.reddit.com/r/gog/comments/cs0dpi/final_fantasy_xiv_integration_for_gog_galaxy_20/](https://www.reddit.com/r/gog/comments/cs0dpi/final_fantasy_xiv_integration_for_gog_galaxy_20/)
[https://github.com/RZetko/galaxy-integration-ffxiv](https://github.com/RZetko/galaxy-integration-ffxiv)

Though, looks like achievements aren't supported yet/are unsupported:

>**Supported**
> - Launching and deleting game
> - Detecting if game is running
>- Syncing friends
>
>**Will be supported in future**
>- Downloading and installing game
>
>**Unsupported**
>- Achievements syncing - XIVAPI supports fetching character achievements but unfortunately due to some issues I wasn't able to make it work
>- Playtime tracking - unsupported by XIVAPI
