### ISSUE TITLE
Minecraft

### ISSUE THREAD

**Issue by Mixaill** [Mixaill/awesome-gog-galaxy#17]
ID whitelisting: ✔ (`minecraft`)

---

https://www.gog.com/forum/general_beta_gog_galaxy_2.0/is_it_possible_to_lauch_minecraft_from_gog_20

**Comment by TouwaStar** [comment]
I will try and tackle this, this week and the next one.

**Comment by Mixaill** [comment]
Requires whitelisting by the way

**Comment by TouwaStar** [comment]
Plugin will be available here https://github.com/TouwaStar/Galaxy_Plugin_Minecraft

**Comment by TouwaStar** [comment]
I think that windows version is pretty much usable right now, hijacking 'Best Buy' until added in galaxy api

**Comment by TouwaStar** [comment]
Mac version looks ok on my mac, @Mixaill  Do you think we can add it to the list?

**Comment by Mixaill** [comment]
Added.

The issue will open till GLX 2.0.5.

**Comment by Mixaill** [comment]
@TouwaStar added in the newest GLX API

**Comment by TouwaStar** [comment]
It looks like it was added to the api but the client itself doesnt handle it yet?

Its not showing up in my client after changing and i can see this in GalaxyClient.log

2019-09-06 09:30:43.983 [Warning][ (0)] [TID 16332][galaxy_client]: Failed to parse plugin manifest, exception: Unrecognized SupportedPlatform value: minecraft

**Comment by Mixaill** [comment]
Yeah, we still have to wait GLX 2.0.5

**Comment by rogsachan** [comment]
2.0.5 is here

**Comment by TouwaStar** [comment]
should be fixed in newest version https://github.com/TouwaStar/Galaxy_Plugin_Minecraft/commit/178d31bda38e9d6b490afbe0b8674864141a44c4
