### ISSUE TITLE
Suggestion improvements to list

### ISSUE THREAD

**Issue by Geroyuni** [Mixaill/awesome-gog-galaxy#27]
Do you think [something like this](https://gist.github.com/Geroyuni/fc2c7cbc338c2eafb1a50744801546c3) works better? This can be further simplified [by removing the library column](https://gist.github.com/Geroyuni/6565f986db88e86a873ac15b92612e37) if library is always a feature (I don't know if there will ever be exceptions).

**Comment by Mixaill** [comment]
GREAT, merged.
