### ISSUE TITLE
Rockstar Game Launcher

### ISSUE THREAD

**Issue by Mixaill** [Mixaill/awesome-gog-galaxy#31]
https://socialclub.rockstargames.com/rockstar-games-launcher

**Comment by Mixaill** [comment]
https://github.com/gogcom/galaxy-integrations-python-api/issues/68

**Comment by Danyelalejandro** [comment]
. Support the request-

**Comment by hightower5** [comment]
Yes, that would be nice. Yesterday I've installed the update of GOG 2.0. Today I've installed the recent Rockstar Games Launcher.

**Comment by tylerbrawl** [comment]
Here you guys go. If you find any issues, then be sure to report them on the plugin's GitHub page.

https://github.com/tylerbrawl/Galaxy-Plugin-Rockstar

**Comment by Mixaill** [comment]
Added, waiting for platform id.

**Comment by Mixaill** [comment]
Platform id was added, waiting for GLX update.
