### ISSUE TITLE
Generic .exe Files

### ISSUE THREAD

**Issue by RelativeProgramming** [Mixaill/awesome-gog-galaxy#4]
It should be possible to add games, which don't come with a launcher.

**Comment by Mixaill** [comment]
The problem is that we have to deal with the user interface to add new games.

One of the possible ways is to use something like JSON configuration file.

**Comment by Mixaill** [comment]
Currently it's impossible to create such kind of integration because of https://github.com/gogcom/galaxy-integrations-python-api/issues/27

**Comment by johny-gog** [comment]
This will be a feature of the app itself. :)

**Comment by rogsachan** [comment]
This is now possible with the atlas update using global search.
