### ISSUE TITLE
Hide tabs

### ISSUE THREAD

**Issue by Krekot** [Mixaill/awesome-gog-galaxy#57]
Could we have option to hide tabs?

![Bez tytułu](https://user-images.githubusercontent.com/580730/69476990-0a4f6700-0de1-11ea-8612-3196d7c251aa.png)

For now, there is only the option to delete tabs.

Also, could we choose which tab we will see on the startup of GOG 2.0? Now there is "All Games" but I would like to switch it to only "Installed Games".

**Comment by FriendsOfGalaxy** [comment]
There is the option to choose Starting Page in Settings-> General -> Starting Page.

It lacks Installed games but its possible to switch to continue previous session if that helps.
![image](https://user-images.githubusercontent.com/48480506/70994951-95b1d480-20cf-11ea-8f34-e83b38b2e2a7.png)

**Comment by Krekot** [comment]
Yes, I know that there is this option but in my opinion Installed would be great option too.

**Comment by Mixaill** [comment]
Please use http://mantis2.gog.com/ to submit feature requests for GLX 2 client.
