### ISSUE TITLE
Add Citra Integration Listing

### ISSUE THREAD

**Issue by j-selby** [Mixaill/awesome-gog-galaxy#6]
Hi!

As an experiment, I authored a GOG Galaxy integration for Citra (a Nintendo 3DS emulator) to see how well the API would work with something more unorthodox and to lay the groundwork for other emulators. Not sure if you want to add it to your list or not - no worries if that isn't something you are looking for.

Link is https://github.com/j-selby/galaxy-integration-citra

Regards.

**Comment by Mixaill** [comment]
Added in 940e08cba8fb2b98410991966d8e4d0afbf8826f
