### ISSUE TITLE
Twitch Game Launcher

### ISSUE THREAD

**Issue by WickedCitizen** [Mixaill/awesome-gog-galaxy#64]
**Identification**
www.twitch.tv

**Integration type**
Launcher

**Present in [Galaxy API available integrations list](https://galaxy-integrations-python-api.readthedocs.io/en/latest/platforms.html)?**
No.

**Supported platforms**
PC

**Store content / licenses**
Twitch Prime Content

**Coverage**
My current Twitch launcher has 125 games available to install.

**Galaxy features**
Which Galaxy 2.0 features could be potentially implemented (for at least one game)? Choose from:
- importing owned games
- detect locally installed games / install / launch / uninstall
- game last played time / total played time
- friends and their statuses
- chat

**Comment by EustaceCS** [comment]
Query.
By Twitch Game Launcher you mean one from https://www.twitch.tv/downloads , right?
I can confirm that https://github.com/nyash-qq/galaxy-plugin-twitch (which is included into this repo/list) works with it absolutely brilliantly.
Case... closed?
