### ISSUE TITLE
Bundlestars / Fanatical

### ISSUE THREAD

**Issue by luxzg** [Mixaill/awesome-gog-galaxy#78]
**Identification**
Fanatical game store, ex Bundlestars
Pretty famous for bundles, even though lately not as great offer... used to be my #2 after Humble.
Store link: https://www.fanatical.com/
Library = orders list / keys: https://www.fanatical.com/en/orders

> Fanatical lets you quickly find what you want from a selection of over 5,000 officially licensed digital games from over 975 publishers.

**Integration type**
store

**Present in [Galaxy API available integrations list](https://galaxy-integrations-python-api.readthedocs.io/en/latest/platforms.html)?**
yes (id: fanatical)

**Supported platforms**
PC / mac / console / web / mobile / ...

**Store content / licenses**
What kind of games does it offer? Their own games, exclusives, other platform keys?
Kind of DRM if there is any: launcher required / in-game login / ...

**Coverage**
> Fanatical lets you quickly find what you want from a selection of over 5,000 officially licensed digital games from over 975 publishers.

**Galaxy features**
- importing owned games

Thanks!

**Comment by nosyn00b** [comment]
Here it is my new plugin, have a try!

https://github.com/nosyn00b/GOG2_Fanatical_Plugin

![image](https://user-images.githubusercontent.com/77177410/105003296-c5e64800-5a32-11eb-9fc7-963e5f2cfcd1.png)
