### ISSUE TITLE
I have made an integration for ScummVM, can you add it to the list?

### ISSUE THREAD

**Issue by micpp42** [Mixaill/awesome-gog-galaxy#85]
I've made a plugin to let GOG Galaxy run games through ScummVM, it's linked here https://github.com/micpp42/gog-galaxy-scummvm
Since GOG doesn't have ScummVM as a platform, I've used the "Amiga" platform for now.
Handles launching games, doesn't track playtime (yet) though.
Can you add it to the list?

**Comment by Mixaill** [comment]
added
