### ISSUE TITLE
Can you add my generic programmatic multiplatform plugin

### ISSUE THREAD

**Issue by AndrewDWhite** [Mixaill/awesome-gog-galaxy#87]
I have created a plugin to allow for the generic programmatic importation of multiple platforms into galaxy. Can you add it to the list?

**Plugin**
https://github.com/AndrewDWhite/GalaxyGenericImporterPlugin

**Description**
Plugin for GOG Galaxy supporting programmatic importation of multiplatform game libraries. Allows for the generic definition of files to be added using user definable regular expressions. Programmatically imports games from predefined folders while allowing for others to be configured by users. Advanced users can also configure how games are are executed and populated into galaxy by editing the configurable regular expressions.

**Supported platforms**
Windows is currently the default supported running platform. System type reported to galaxy is defaulted to test; while an advanced end user can use the workaround utilized by other plugins to place and configure multiple instances of the plugin. The plugin supports automatically populating games from the following platforms but others will be added later. Execution is subject to an appropriate execution platform/emulator installed and either configured or placed in the default locations assumed by the plugin.

- Sega Dreamcast
- Game Boy Advance
- Game Boy Color
- Gamecube
- Sega Genesis
- Nintendo 64
- Nintendo DS
- Nintendo Entertainment System
- Playstation 2
- Playstation 3
- Playstation Portable
- Playstation 1
- Super Nintendo Entertainment System
- Wii
- XBOX
- Wii U
- Arcade
- Amazon Games

**Galaxy features**
The following is the current capabilities for the plugin but other features are planned to be researched for their generic viability.

Supported:

- importing owned games
- detect locally installed games / install / launch
- game last played time / total played time

Unsupported:
- uninstall
- game achievements
- friends and their statuses
- chat

**Comment by Mixaill** [comment]
fixed in 3768d6f440e9ea744f5684f4d892106d35ffc0d8
