### ISSUE TITLE
Nuuvem, FX Store, IndieGala , PlayFire [Request]

### ISSUE THREAD

**Issue by RaptorPharaoh** [Mixaill/awesome-gog-galaxy#9]
Hello, i want to ask if exist the possibility to add plugins of these stores, because these sites have an own DRM or DRM free games, and will be very nice have it in Galaxy to accomplish the most complete library. Sorry if this isn't the correct format, but I'm new in GitHub. Thank you.

Indiegala = It's similar to Humble Bundle DRM Free downloads, probably this is the easiest to make.

Nuuvem = The same, but a few games requires a DRM software to start, i.e. Prince of Persia and DRM Tages.

FX Store = This require a Firefox web browser and an extension for it, today you can download a simple Firefox app.

Playfire = This is for DRM Free from Green Man Gaming, it's a software like Origin or Steam.

I really appreciate if you can create at least a plugin to see the library, with this in my opinion almost stores will be complete. :) Thank you and excellent work, a very BIG thank you for creating this plugins, are very great.

**Comment by UncleGoogle** [comment]
None of those are listed supported platforms
https://galaxy-integrations-python-api.readthedocs.io/en/latest/platforms.html

so even if someone create integration it won't work with Galaxy.

I think you should repost this issue on galaxy api site: 
https://github.com/gogcom/galaxy-integrations-python-api/issues

**Comment by UncleGoogle** [comment]
Also - are does games DRM-free? 
First impression is that indiegala offers Steam and Uplay keys (no filter for drm-free in store)

Indiegala has just few DMR-free games:
https://www.nuuvem.com/catalog/drm/drm-free

The rest will be handled by other integrations (at least, when you redeem purchased keys).

BTW
Would like to have support for Steam/Uplay ect. games in humblebundle - just to show them or open page where they can be redeem? I don't know to workflow for stores you listed - but are they offering redeeming keys from theirs library like humble does?

**Comment by RaptorPharaoh** [comment]
Hello @UncleGoogle 

Thanks for your reply. Oh ok, I don't know about that list of supported sites, its a shame, nothing to do then :( how you say me I'll repost this on that site.

About IndieGala I don't sure about how obtain DRM Free games, but I have a list of them in my library, you need to go to your Library and select the option "Showcase Library", then appear a list of DRM free games to download like in HumbleBundle.

About Nuuvem, thanks for the list you give me, my mistake, today appears they don't have a lot of DRM Free, I put it on the list because I bought in that store a few times and at that time they have  a lot of DRM Free games, i.e. I bought the Prince of Persia collection and all was DRM Free, now they're Uplay platform, probably they removed all DRM Free and changed it for keys in Steam or Uplay.

About Playfire, probably the same of Nuuvem, in the past, Green Man Gaming has games in DRM Free format, you need a software called PlayFire to access them, works exactly than steam, but I suppose today they only have keys for steam or another platform, in any case I leave here a link:

[https://greenmangaming.zendesk.com/hc/en-us/articles/217493857-Installing-the-Playfire-Client](url)

About FX Store, this store has a very good exclusive games and awesome anthologies, but their installation method is really bad, is a store like steam, but you need a browser extension to download the games you bought. This is the link [Spain store] and they don't offer keys :( :

[https://juegos.fxinteractive.com/](url)

[https://juegos.fxinteractive.com/fx/catalogo.php](url)

And yes, I would like see support to see the redeem pages in the humble bundle plugin :)

**Comment by Mixaill** [comment]
Superseded by #12 #13 #14 #15
