### ISSUE TITLE
Community integrations working poorly

### ISSUE THREAD

**Issue by RayRJJackson** [Mixaill/awesome-gog-galaxy#90]
**Problem**
I tried to integrate AGAIN uPlay and Steam, without succcess. The settings tell me that they're offline. Also the integrations don't stay integrated into the account, but randomly disconnect for no reason.

**Comment by Mixaill** [comment]
Hello,

I recommend you to report it individually to each integration bugtracker

* Steam: https://github.com/FriendsOfGalaxy/galaxy-integration-steam/issues
* Uplay: https://github.com/FriendsOfGalaxy/galaxy-integration-uplay/issues
